---
abstract: 'A Trait for SessionInstantiation to enable extra initialization'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla version 1.092680'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Trait-ExtraInitialization
requires:
  POEx::Role::SessionInstantiation: 0.092673
  Test::More: 0.92
resources:
  repository: git://github.com/nperez/pxtei.git
version: 0.092720
